# Generated by Django 3.2.9 on 2021-12-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=100)),
                ('release_date', models.IntegerField(default=None)),
                ('label', models.CharField(default=None, max_length=100)),
                ('genre', models.CharField(default=None, max_length=100)),
                ('type_of_record', models.CharField(choices=[('single', 'Single Release'), ('EP', 'Extended Project'), ('LP', 'Long Play'), ('V/A', 'Artist Compilation')], default=None, max_length=100)),
                ('is_vinyl_only', models.BooleanField(default=None)),
                ('link', models.CharField(default=None, max_length=200)),
            ],
        ),
    ]
