# Generated by Django 3.2.9 on 2021-12-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='artists',
            field=models.ManyToManyField(to='artists.Artist'),
        ),
        migrations.AlterField(
            model_name='record',
            name='genre',
            field=models.CharField(choices=[('UKG', 'UKG'), ('Breaks', 'Breaks'), ('Jungle', 'Jungle'), ('House', 'House'), ('Drum and Bass', 'Drum and Bass'), ('Techno', 'Techno'), ('Dubstep', 'Dubstep'), ('Other', 'Other')], default=None, max_length=100),
        ),
    ]
