# Generated by Django 3.2.9 on 2021-12-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_auto_20211201_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='jwt_auth.user'),
            preserve_default=False,
        ),
    ]
