# Generated by Django 3.2.9 on 2021-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type_of_record',
            field=models.CharField(choices=[('Single', 'Single Release'), ('EP', 'Extended Project'), ('LP', 'Long Play'), ('V/A', 'Artist Compilation')], default=None, max_length=100),
        ),
    ]
