# Generated by Django 3.2.9 on 2021-12-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='soundcloud_link',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
