# Generated by Django 3.2.9 on 2021-12-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_soundcloud_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='soundcloud_link',
        ),
    ]
